version: "3.8"

services:
  telegram:
    build: telegram/
    environment:
      ROOT_DIR: "/home/archive_bot/docs_repo/"
      ADMIN_ID: "Owner ID"
      API_ID: "Api ID"
      API_HASH: "Api Hash"
      BOT_TOKEN: "Telegram Bot Token"
      PAGINATION_COUNT: 8
      DB_URL: "postgresql+psycopg2://archive_bot:archive_bot@postgresql:5432/archive_bot"
    depends_on:
      - redis
      - postgresql
    networks:
      - db
    volumes:
      - "./docs_repo:/home/archive_bot/docs_repo"
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: "archive_bot"
      POSTGRES_DB: "archive_bot"
      POSTGRES_PASSWORD: "archive_bot"
    networks:
      - db
    volumes:
      - "./db_postgresql:/var/lib/postgresql/data"
  redis:
    image: redis:latest
    networks:
      - db
    volumes:
      - "./db_redis:/data"
  pgweb:
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    links:
      - postgresql:postgresql
    environment:
      - DATABASE_URL=postgresql://archive_bot:archive_bot@postgresql:5432/archive_bot?sslmode=disable
      - PGWEB_AUTH_USER=archive_bot
      - PGWEB_AUTH_PASS=archive_bot
    depends_on:
      - postgresql
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  docs_repo:
  db_postgresql:
  db_redis:
