"""File_id field added.

Revision ID: 0744c786bf97
Revises: d86d8f662061
Create Date: 2023-12-24 00:52:45.116167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0744c786bf97'
down_revision: Union[str, None] = 'd86d8f662061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('persian_title', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['directory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directory_name'), 'directory', ['name'], unique=True)
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('persian_title', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('directory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['directory_id'], ['directory.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['bot_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id'),
    sa.UniqueConstraint('path')
    )
    op.create_index(op.f('ix_document_title'), 'document', ['title'], unique=True)
    op.add_column('statistics', sa.Column('downloaded', sa.Integer(), nullable=True))
    op.add_column('statistics', sa.Column('uploaded', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'statistics', ['id'])
    op.drop_column('statistics', 'download')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('download', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'statistics', type_='unique')
    op.drop_column('statistics', 'uploaded')
    op.drop_column('statistics', 'downloaded')
    op.drop_index(op.f('ix_document_title'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_directory_name'), table_name='directory')
    op.drop_table('directory')
    # ### end Alembic commands ###
