"""Downloaded count field added to document.

Revision ID: 15e19983ba3f
Revises: a0a2df469e9a
Create Date: 2024-01-12 00:52:54.884572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e19983ba3f'
down_revision: Union[str, None] = 'a0a2df469e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('download_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'download_count')
    # ### end Alembic commands ###
