"""add slug to the directory model.

Revision ID: 454794d1e71e
Revises: 5125a61f9d0a
Create Date: 2025-02-12 22:27:24.931394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454794d1e71e'
down_revision: Union[str, None] = '5125a61f9d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directory', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_directory_slug'), 'directory', ['slug'], unique=True)
    op.create_unique_constraint(None, 'moderator_user', ['pk'])
    op.create_unique_constraint(None, 'users', ['pk'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'moderator_user', type_='unique')
    op.drop_index(op.f('ix_directory_slug'), table_name='directory')
    op.drop_column('directory', 'slug')
    # ### end Alembic commands ###
