"""initial migrations

Revision ID: 5125a61f9d0a
Revises: 
Create Date: 2025-02-12 01:38:09.009127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5125a61f9d0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_category_title'), 'category', ['title'], unique=False)
    op.create_table('directory',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('parent_dir_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_dir_pk'], ['directory.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_directory_title'), 'directory', ['title'], unique=False)
    op.create_table('log',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_log_level'), 'log', ['level'], unique=False)
    op.create_table('moderator_user',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('pk')
    )
    op.create_index(op.f('ix_moderator_user_email'), 'moderator_user', ['email'], unique=True)
    op.create_table('statistics',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('users_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('tag',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_tag_title'), 'tag', ['title'], unique=False)
    op.create_table('teacher_cv',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_teacher_cv_full_name'), 'teacher_cv', ['full_name'], unique=False)
    op.create_table('category_tag_rel',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('category_pk', sa.Integer(), nullable=False),
    sa.Column('tag_pk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_pk'], ['category.pk'], ),
    sa.ForeignKeyConstraint(['tag_pk'], ['tag.pk'], ),
    sa.PrimaryKeyConstraint('pk', 'category_pk', 'tag_pk')
    )
    op.create_table('users',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('field_of_study', sa.String(), nullable=False),
    sa.Column('notifications', sa.Boolean(), nullable=False),
    sa.Column('moderator_user_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['moderator_user_pk'], ['moderator_user.pk'], ),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('moderator_user_pk'),
    sa.UniqueConstraint('pk')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('file_in_cloud_storage',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hard_uploaded', sa.Boolean(), nullable=False),
    sa.Column('is_promoted', sa.Boolean(), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('upload_datetime', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by_pk', sa.Integer(), nullable=False),
    sa.Column('directory_pk', sa.Integer(), nullable=True),
    sa.Column('raw_location', sa.String(), nullable=False),
    sa.Column('verification_time', sa.DateTime(), nullable=True),
    sa.Column('verified_by_pk', sa.Integer(), nullable=False),
    sa.Column('teacher_pk', sa.Integer(), nullable=True),
    sa.CheckConstraint('(is_active = TRUE AND title IS NOT NULL AND description IS NOT NULL) OR\n                                      (is_active = FALSE AND (title IS NULL OR description IS NULL))'),
    sa.ForeignKeyConstraint(['directory_pk'], ['directory.pk'], ),
    sa.ForeignKeyConstraint(['teacher_pk'], ['teacher_cv.pk'], ),
    sa.ForeignKeyConstraint(['uploaded_by_pk'], ['users.pk'], ),
    sa.ForeignKeyConstraint(['verified_by_pk'], ['moderator_user.pk'], ),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('raw_location')
    )
    op.create_index(op.f('ix_file_in_cloud_storage_title'), 'file_in_cloud_storage', ['title'], unique=False)
    op.create_table('file_in_telegram_cloud',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('in_tel_title', sa.String(), nullable=False),
    sa.Column('file_pk', sa.String(), nullable=False),
    sa.Column('storage_pk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['storage_pk'], ['file_in_cloud_storage.pk'], ),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('storage_pk')
    )
    op.create_index(op.f('ix_file_in_telegram_cloud_file_pk'), 'file_in_telegram_cloud', ['file_pk'], unique=False)
    op.create_index(op.f('ix_file_in_telegram_cloud_in_tel_title'), 'file_in_telegram_cloud', ['in_tel_title'], unique=False)
    op.create_table('storage_file_user_like_rel',
    sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_in_cloud_storage_pk', sa.Integer(), nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_in_cloud_storage_pk'], ['file_in_cloud_storage.pk'], ),
    sa.ForeignKeyConstraint(['user_pk'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('pk', 'file_in_cloud_storage_pk', 'user_pk')
    )
    op.create_table('tag_file_rel',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('file_pk', sa.Integer(), nullable=False),
    sa.Column('tag_pk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_pk'], ['file_in_cloud_storage.pk'], ),
    sa.ForeignKeyConstraint(['tag_pk'], ['tag.pk'], ),
    sa.PrimaryKeyConstraint('pk', 'file_pk', 'tag_pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_file_rel')
    op.drop_table('storage_file_user_like_rel')
    op.drop_index(op.f('ix_file_in_telegram_cloud_in_tel_title'), table_name='file_in_telegram_cloud')
    op.drop_index(op.f('ix_file_in_telegram_cloud_file_pk'), table_name='file_in_telegram_cloud')
    op.drop_table('file_in_telegram_cloud')
    op.drop_index(op.f('ix_file_in_cloud_storage_title'), table_name='file_in_cloud_storage')
    op.drop_table('file_in_cloud_storage')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('category_tag_rel')
    op.drop_index(op.f('ix_teacher_cv_full_name'), table_name='teacher_cv')
    op.drop_table('teacher_cv')
    op.drop_index(op.f('ix_tag_title'), table_name='tag')
    op.drop_table('tag')
    op.drop_table('statistics')
    op.drop_index(op.f('ix_moderator_user_email'), table_name='moderator_user')
    op.drop_table('moderator_user')
    op.drop_index(op.f('ix_log_level'), table_name='log')
    op.drop_table('log')
    op.drop_index(op.f('ix_directory_title'), table_name='directory')
    op.drop_table('directory')
    op.drop_index(op.f('ix_category_title'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
