"""add moderator user and teacher models. adding some other fields

Revision ID: 70f914e4ba95
Revises: 9b9b1d9705fe
Create Date: 2024-12-02 02:24:05.526074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70f914e4ba95'
down_revision: Union[str, None] = '9b9b1d9705fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderator_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('auth_token', sa.String(), nullable=True),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_moderator_user_email'), 'moderator_user', ['email'], unique=True)
    op.create_table('teacher_cv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_cv_full_name'), 'teacher_cv', ['full_name'], unique=False)
    op.create_index(op.f('ix_category_title'), 'category', ['title'], unique=False)
    op.create_index(op.f('ix_directory_title'), 'directory', ['title'], unique=False)
    op.add_column('file_in_telegram_cloud', sa.Column('verification_time', sa.DateTime(), nullable=False))
    op.add_column('file_in_telegram_cloud', sa.Column('verified_by_id', sa.Integer(), nullable=False))
    op.add_column('file_in_telegram_cloud', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'file_in_telegram_cloud', 'teacher_cv', ['teacher_id'], ['id'])
    op.create_foreign_key(None, 'file_in_telegram_cloud', 'moderator_user', ['verified_by_id'], ['id'])
    op.drop_column('file_in_telegram_cloud', 'creation_date')
    op.add_column('users', sa.Column('moderator_user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'users', ['moderator_user_id'])
    op.create_foreign_key(None, 'users', 'moderator_user', ['moderator_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'moderator_user_id')
    op.add_column('file_in_telegram_cloud', sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'file_in_telegram_cloud', type_='foreignkey')
    op.drop_constraint(None, 'file_in_telegram_cloud', type_='foreignkey')
    op.drop_column('file_in_telegram_cloud', 'teacher_id')
    op.drop_column('file_in_telegram_cloud', 'verified_by_id')
    op.drop_column('file_in_telegram_cloud', 'verification_time')
    op.drop_index(op.f('ix_directory_title'), table_name='directory')
    op.drop_index(op.f('ix_category_title'), table_name='category')
    op.drop_index(op.f('ix_teacher_cv_full_name'), table_name='teacher_cv')
    op.drop_table('teacher_cv')
    op.drop_index(op.f('ix_moderator_user_email'), table_name='moderator_user')
    op.drop_table('moderator_user')
    # ### end Alembic commands ###
