"""Notification field and study field added.

Revision ID: a0a2df469e9a
Revises: ce38d0ce2ac9
Create Date: 2024-01-11 17:13:43.749536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a2df469e9a'
down_revision: Union[str, None] = 'ce38d0ce2ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_user', sa.Column('receive_notifications', sa.Boolean(), nullable=True))
    op.add_column('bot_user', sa.Column('study_field', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_user', 'study_field')
    op.drop_column('bot_user', 'receive_notifications')
    # ### end Alembic commands ###
