"""convert downloaded and uploaded to big int.

Revision ID: d8460a479b31
Revises: acc892e9bcd3
Create Date: 2024-01-26 18:15:22.076513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8460a479b31'
down_revision: Union[str, None] = 'acc892e9bcd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_user', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.add_column('bot_user', sa.Column('permissions', sa.String(), nullable=True))
    op.alter_column('statistics', 'downloaded',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('statistics', 'uploaded',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statistics', 'uploaded',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('statistics', 'downloaded',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('bot_user', 'permissions')
    op.drop_column('bot_user', 'is_superuser')
    # ### end Alembic commands ###
